apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  description: Backstage for CloudNomster
  annotations:
    github.com/project-slug: CloudNomster/backstage
    goharbor.io/repository-slug: library/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:team-nomster
  lifecycle: production