apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: CloudNomster/backstage
    argocd/app-name: backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: TechMonkeys:markku@techmonkeys.se
  lifecycle: production
