name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: nomsterbuilder
#    container: node:20-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm install --global yarn

      - name: yarn install
        run: yarn install --immutable
        shell: bash

      - name: Build typedefs
        run: yarn tsc

      - name: Build backend
        run: yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml

      - name: Build image
        run: yarn build-image
        
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: "{{defaultContext}}"
#          file: packages/backend/Dockerfile
#          push: false
#          tags: user/backstage:latest
#          no-cache: true
