name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: nomsterbuilder
#    container: node:20-bookworm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm install --global yarn

      - name: yarn install
        run: yarn install --immutable
        shell: bash

      - name: Build typedefs
        run: yarn tsc

      - name: Build backend
        run: yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml

      - name: Build image
        run: yarn build-image
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ secrets.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}
          
      - name: Push to registry
        run: |
          docker tag backstage ${{ secrets.HARBOR_HOST }}/library/backstage:latest
          docker push backstage:latest
