name: Backstage build and push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: nomsterbuilder
    # container: node:20-bookworm

    steps:
      - name: send STARTING to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          color: "yellow"
          message: "${{ github.repository }} build starting: ${{ github.event.head_commit.message }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm install --global yarn

      - name: yarn install
        run: yarn install --immutable
        shell: bash

      - name: Build typedefs
        run: yarn tsc

      - name: Build backend
        # run: yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml
        run: yarn build:backend

      - name: Build image
        run: yarn build-image
        env:
          DOCKER_BUILDKIT: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_HOST }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Push to registry
        run: |
          docker tag backstage ${{ secrets.HARBOR_HOST }}/library/backstage:latest
          docker push ${{ secrets.HARBOR_HOST }}/library/backstage:latest

      - name: send COMPLETED to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          color: "{{#success build.status}}green{{else}}red{{/success}}"
          message: "{{#success build.status}}✅{{else}}❌{{/success}} ${{ github.repository }} build succeeded: ${{ github.event.head_commit.message }}"
  